apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.app.name }}-tls
  namespace: {{ .Values.app.namespace }}
spec:
  secretName: {{ .Values.app.name }}-tls
  issuerRef:
    name: {{ .Values.app.certIssuer | default "local-amazone" }}
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: {{ .Values.app.url }}
  dnsNames:
  - {{ .Values.app.url }}