app:
  name: amazone-gateway
  image: killiankopp/api-gateway:amazone-1.0.4
  replicas: 1
  url: api.amazone.lan
  namespace: amazone
  # Utiliser l'issuer local qui fonctionne
  certIssuer: local-amazone