app:
  name: amazone-gateway
  image: killiankopp/api-gateway:amazone-1.0.4
  replicas: 1
  url: api.amazone.lan
  namespace: amazone
  # Changez l'issuer pour Let's Encrypt
  certIssuer: letsencrypt-staging  # ou letsencrypt-prod pour la production